[workspace]
resolver = "2"
members = [
  "qmushclient",
  "qmushclient-derive",
  "qt/qt_core",
  "qt/qt_gui",
  "qt/qt_network",
  "qt/qt_ui_tools",
  "qt/qt_widgets",
  "ritual/qt_ritual_build",
  "ritual/qt_ritual_common",
  "ritual/ritual_build",
  "ritual/ritual_common",
]
