[package]
name = "qmushclient"
version = "0.0.0"
authors = ["Joshua Booth <joshua.n.booth@gmail.com>"]
edition = "2018"
publish = false
description = "Cross-platform MUD game client based on Nick Gammon's MUSHclient, built with Rust and the QT framework"
repository = "https://github.com/jnbooth/qmushclient"

[features]
show-special = []

[dependencies]
bincode = "1.3.3"
chrono = "0.4.19"
cpp_core = "0.6.0"
flate2 = "1.0.20"
hashbrown = { version = "0.11.2", features = ["serde"] }
iter_chunks = { path = "lib/iter-chunks" }
libc = "0.2.92"
mlua = { version = "0.5.4", features = ["luajit", "vendored"] }
once_cell = "1.7.2"
qmushclient_derive = { path = "qmushclient-derive" }
qt_core = { path = "lib/qt_core" }
qt_gui = { path = "lib/qt_gui" }
qt_network = { path = "lib/qt_network" }
qt_ui_tools = { path = "lib/qt_ui_tools" }
qt_widgets = { path = "lib/qt_widgets" }
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.64"
unicase = "2.6.0"
uuid = { version = "0.8.2", features = ["v4"] }

[build-dependencies]
qt_ritual_build = { path = "lib/ritual/qt_ritual_build" }
